### ISSUE TITLE
Can you please try an implementation of Kryo Serializer

### ISSUE THREAD

**Issue by mozinrat** [spring-projects/spring-integration-extensions#151]
We are using hazelcast as an standalone server and want to make it unaware of Java objects on web server. We had used a Json envelope for this but it would be a cool feature if you can figure out a Kryo envelope out of box. Thanks really great work..

**Comment by artembilan** [comment]
The Spring Integration since 4.2 provides support for Kryo (de)serialization: http://spring.io/blog/2015/08/17/spring-integration-4-2-release-candidate-is-available, http://docs.spring.io/spring-integration/docs/4.2.0.BUILD-SNAPSHOT/reference/html/messaging-transformation-chapter.html#codec.

Let us know if it is sufficient for you!

**Comment by artembilan** [comment]
I'm considering the `EncodingPayloadTransformer`, `DecodingTransformer`, `CodecMessageConverter` with Kryo support in the Spring Integration Core since `4.2` as valid solution for this request.
See the JIRAs on the matter: 
https://jira.spring.io/browse/INT-3779
https://jira.spring.io/browse/INT-3776

Thank you for feedback anyway!
