### ISSUE TITLE
zip: Message header for ZIP_ENTRY_PATH is always empty

### ISSUE THREAD

**Issue by robmoore** [spring-projects/spring-integration-extensions#156]
I'm trying to use the ZIP_ENTRY_PATH value but I notice it's always empty when setting a breakpoint in UnZipResultSplitter. I'm guessing that this is because I'm using the BYTE_ARRAY zip result type on the zip transformer but it would be nice if there were some way to preserve the containing file's name.

**Comment by artembilan** [comment]
Hello @robmoore !

Please, share the code to reproduce, because we have the test case on the matter (`UnZip2FileTests`):
```
<int:chain input-channel="input" output-channel="out">
	<int-zip:unzip-transformer result-type="BYTE_ARRAY"/>
	<int:splitter>
		<bean class="org.springframework.integration.zip.splitter.UnZipResultSplitter"/>
	</int:splitter>
</int:chain>
```
And I can confirm that the result looks like:
![unzipped](https://cloud.githubusercontent.com/assets/1071590/12342263/ea64d8bc-baf6-11e5-8a19-bbf4cbb2de70.png)

Exactly restored an archive structure from the `countries.zip`: https://github.com/spring-projects/spring-integration-extensions/blob/master/spring-integration-zip/src/test/resources/testzipdata/countries.zip

**Comment by robmoore** [comment]
Fair enough, Artem. I should have mentioned that the FileHeaders.FILENAME value is populated with the file name (eg, `de`). It's just the ZipHeaders.ZIP_ENTRY_PATH value that's an empty string:

From UnZipResultSplitter:
```
final Message<Object> splitMessage = MessageBuilder.withPayload(entry.getValue())
					.setHeader(FileHeaders.FILENAME, filename)
					.setHeader(ZipHeaders.ZIP_ENTRY_PATH, path).build();
```

**Comment by artembilan** [comment]
Right, it is if all files in the zip are in root directory.
I say this because I see this picture from our test-case:
```
unzippedEntries = {TreeMap@2572}  size = 5
 0 = {TreeMap$Entry@2574} "continents/asia.txt" -> 
 1 = {TreeMap$Entry@2606} "continents/europe.txt" -> 
 2 = {TreeMap$Entry@2607} "de.txt" -> 
 3 = {TreeMap$Entry@2608} "fr.txt" -> 
 4 = {TreeMap$Entry@2609} "pl.txt" -> 
messages = {ArrayList@2573}  size = 0
entry = {TreeMap$Entry@2574} "continents/asia.txt" -> 
path = "continents/"
filename = "asia.txt"
```

So, `path` isn't empty and it is really is used from the `directory-expression="'${workDir}/' + headers.zip_entryPath"` to create the sub-directory in the target dir. See the screenshot above.

Still not sure where is your problem.
Need kinda some code to see from your side...

**Comment by robmoore** [comment]
Thanks. I was trying to get the name of the zip file these files are from but it doesn't look like that's one of the headers available here.

**Comment by artembilan** [comment]
Do you mean the name of the source file, something like `countries.zip`?

You can do that on yourself before the `<int-zip:unzip-transformer>` using `<header-enricher>` and some custom header for your purpose. 

Sorry, but this fully different story and doesn't reflect the subject of the issue.

And... similar questions are StackOverflow candidates.

Anyway I'm glad to be helpful.

**Comment by robmoore** [comment]
Thanks, Artem. It might be helpful to provide some more details in the docs about what each of these headers represent. I understand it after your example but didn't before just based on the docs.
