### ISSUE TITLE
Do we have spring-integration-smb release version

### ISSUE THREAD

**Issue by agrawalchetan** [spring-projects/spring-integration-extensions#168]
do we have release the spring integration smb version or is there any plan to release it in near future. with snapshot version, we are not able to download it and we are planning to have released version as we are moving our code to production environment.

**Comment by artembilan** [comment]
Well, we can release that project as an early prototype in version like `0.5.0`.
But the problem that we will upgrade it to the latest dependencies versions.
Currently the project is based on the EOL Spring Integration `2.2.1`. 

So, the question to you: which Spring Integration version do you use in your project?
Would it be so difficult to you to upgrade to the latest `4.3.6`?
Since version `3.0.x` is out of support starting this year, I'm totally not thrilled to release SMB extension even with that version.

**Comment by agrawalchetan** [comment]
Hi, we are using spring boot version 1.4.2  and spring-integration version 4.3.5. although we can move to 4.3.6 as well.

**Comment by artembilan** [comment]
That's great!
So, we are upgrading `SI-SMB` project and releasing the next week!
That will be something like `0.5.0.RELEASE`.
Does that work for you?

**Comment by agrawalchetan** [comment]
Thank you!!. please let me know once you will release the next version.

**Comment by artembilan** [comment]
@agrawalchetan ,

please, find a PR #170 on the matter.
Let us know if you are fine with all those changes.

Thank you!

**Comment by agrawalchetan** [comment]
thank you @artembilan, i am fine with the changes. please let me know release version artifact id once changes are done.

**Comment by artembilan** [comment]
@agrawalchetan ,

We have just released `SI-SMB-0.5.0.RELEASE`: https://spring.io/blog/2017/01/18/spring-integration-extension-for-smb-0-5-0-is-available

Thank you for your request!

**Comment by agk2** [comment]
@artembilan,
Thanks for releasing SI-SMB-0.5.0Release it really help full in our project.
Any plan to release SI-SMB-1.0.Release with SMB Outbound Channel Adapter?

**Comment by artembilan** [comment]
@agk2 ,

We don't have requirements and demands on this project, so there is just no dedicated resources to go ahead. We all are busy with more important projects.
However contribution is always welcome and we will be more than happy to review, merge and eventually release improvements.

Thanks for the interest to the project any way!
