### ISSUE TITLE
Milestone update for Spring Integration Hazelcast

### ISSUE THREAD

**Issue by etorres** [spring-projects/spring-integration-extensions#169]
Hi,

First of all, million thanks for your awesome work integrating Hazelcast in Spring.

We are expecting with great expectation the release of a new milestone. Any plans?

Regards,

Erik

**Comment by artembilan** [comment]
@etorres ,

Of course, first of all, thank you for the attention to the project! 😄 

Well, that isn't a bit deal to release, but the question is: what do you see in changes of that project that it requires Milestone?

Yes, unfortunately, there is no progress in that extension for a while, just because there is no external requests. We are community driven team, therefore if there is no feedback from you, guys, than it might mean that you don't need such a project and we just do what piques interest.

We always welcome contribution, because our mind may be busy with something else. And since we don't use this library ourselves, we don't pay so much attention how is it going.

So, just let us know what you would like to see in that next Milestone and if you won't mind to contribute eventually. We always are happy to help with review, like that was from day first of this project!

**Comment by etorres** [comment]
Hi Artem,

Thanks for your prompt response. We are specifically interested in leader election. We found that this feature is available in the snapshot repository, and it would be great to have it in the milestone also.

Cheers.

**Comment by ccaromen** [comment]
Artem,
I am also interested in having this feature in the Milestone.
Currently, I am involved in a project, in which my team is using this feature from the snapshot repository.
Thank you

**Comment by artembilan** [comment]
OK, guys.
Thank you for feedback!

I'll come back to you next already with M2 release.
After that we can go straightforward to RC over a week or so and than quickly to the GA.
 
But don't hesitate to provide any feedback.
Even if you can't contribute, requests for new features are welcome!

**Comment by artembilan** [comment]
Guys, we have just release `spring-integration-hazelcast-1.0.0.M2`: https://spring.io/blog/2017/01/23/spring-integration-extension-for-hazelcast-1-0-0-m2-available
